server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719  #默认8719，应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用HttpServer
      #sentinel配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848 # nacos配置中心的地址
            dataId: cloudalibaba-sentinel-service # 定义配置信息时的选项
            groupId: DEFAULT_GROUP # 定义配置信息时的选项
            data-type: json  # 定义配置信息时的选项
            rule-type: flow
#            [
#              {
#                "resource": "/testA",
#                "limitApp": "default",
#                "grade": 1,
#                "count": 1,
#                "strategy": 0,
#                "controlBehavior": 0,
#                "clusterMode": false
#              },
#              {
#                "resource": "/testB",
#                "limitApp": "default",
#                "grade": 1,
#                "count": 2,
#                "strategy": 0,
#                "controlBehavior": 0,
#                "clusterMode": false
#              }
#            ]

#健康状况监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
#  流控
#  直接：指定路径进行控制
#  关联：testB请求完发送到testA，B请求过多时，通过关联，用A来限制B的请求数量
#  链路：sleuth,多个微服务之间的调用
#  快速失败：超过阈值就阻塞
#  Warm Up 预热：规定时间达到多少请求，默认值为3
#  排队等待：排队请求，超时会429
#
#  熔断
#  慢调用比例：在统计时长内达到最小请求数量
#  异常比例：超过阈值比例进行熔断
#
#  热点限流：对热门商品制定的规则